CREATE TABLE IF NOT EXISTS users(
    userId BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(75) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    firstName VARCHAR(60) NOT NULL,
    lastName VARCHAR(60) NOT NULL,
    imageURL VARCHAR(255),
    role ENUM('student', 'admin') DEFAULT 'student',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clubs(
    clubId BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT NOT NULL,
    imageURL VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events(
    eventId BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(75) NOT NULL,
    description TEXT NOT NULL,
    featured BOOLEAN DEFAULT FALSE,
    location VARCHAR(100) NOT NULL,
    eventTime TIMESTAMP NOT NULL,
    imageURL VARCHAR(255),
    clubId BIGINT(20) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (clubId) REFERENCES clubs(clubId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS registrations(
    registrationId BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    userId BIGINT(20) NOT NULL,
    eventId BIGINT(20) NOT NULL,
    registrationTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE,
    FOREIGN KEY (eventId) REFERENCES events(eventId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS eventCategories(
    categoryId BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(50) UNIQUE NOT NULL,
    eventId BIGINT(20) NOT NULL,
    FOREIGN KEY (eventId) REFERENCES events(eventId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS memberships(
    membershipId BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    userId BIGINT(20) NOT NULL,
    clubId BIGINT(20) NOT NULL,
    joinTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE,
    FOREIGN KEY (clubId) REFERENCES clubs(clubId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS refreshTokens(
    tokenId BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    userId BIGINT(20) NOT NULL,
    token VARCHAR(255) NOT NULL,
    expiryTime TIMESTAMP NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE
);